[theme]
primaryColor = "#0096D6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
